### ISSUE TITLE
Peanut candy with salt requires one tenth the peanut paste, gives weird nutrition

### ISSUE THREAD

**Issue by adam80027** [l33tmaan/EFRecipes#11]
Salted peanut candy seems to erroneously require one tenth the usual amount of peanut paste, compared to unsalted.

Unsalted: 616 total sat for 0.1L peanut paste + 0.1L syrup. 320 of that is bonus protein.
![image](https://user-images.githubusercontent.com/26748789/220472879-49c4b850-2c36-4865-ab7d-a4c49f0a8c31.png)

Salted: 328 total sat for **0.01L** peanut paste + 0.1L syrup + 1 salt. 32 of that is bonus protein.
![image](https://user-images.githubusercontent.com/26748789/220472744-d3ceaadb-4967-432d-bb79-4380ae111c34.png)

From candy.json, looks like the salted version only takes quantity 1 peanut paste, whereas the unsalted takes 10.
![image](https://user-images.githubusercontent.com/26748789/220475279-457d7db9-68ac-4603-aad4-afeece7242b1.png)

**Comment by l33tmaan** [comment]
Good catch. I've fixed the problem. Thank you! :D
