### ISSUE TITLE
Steam deck compatibility?

### ISSUE THREAD

**Issue by ncottrill** [l33tmaan/EFRecipes#12]
A friend of mine is trying to connect to our server using Steam Deck. The Expanded Foods mod appears to be crashing so he cannot join.

Running on 64 bit Linux with 14 GB.
Game Version: v1.17.11 (Stable)
2/26/2023 9:32:08 PM: Critical error occurred
Loaded Mods: animalcages@2.0.6, bettercrates@1.5.3, extrachests@1.6.2, harptech@0.2.3, RockBlocks@1.0.0, game@1.17.11, carryon@0.10.3, morespace@1.0.1, th3expansion@1.0.2, creative@1.17.11, survival@1.17.11, VsTrashcan@1.0.1
System.Exception: Don't know how to instantiate item of class 'ExpandedFood' did you forget to register a mapping?
at Vintagestory.Common.ClassRegistry.CreateItem (System.String itemClass) [0x0001e] in <3352cf17b586476e962abf3ce6c3aa95>:0
at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket (Packet_ItemType packet, Vintagestory.API.Common.IWorldAccessor world, Vintagestory.Common.ClassRegistry registry) [0x00000] in <3352cf17b586476e962abf3ce6c3aa95>:0
at Vintagestory.Client.NoObf.GeneralPacketHandler.PopulateItems (System.Collections.Generic.List`1[T] items, System.Int32 listSize) [0x00051] in <3352cf17b586476e962abf3ce6c3aa95>:0
...

This forum post (see link) mentions that it is possible that the mod isn't set up for Linux version of the game? Is that right?
https://www.vintagestory.at/forums/topic/8147-vintage-story-on-steam-deck/#:~:text=From%20the%20Games%20category%2C%20right,share%2Fapplications%20and%20open%20at. "Some mods work well with Windows and Linux, but not Linux Flatpak version of Vintage Story.  The common reason for that is mod developers reference libraries in a way that can't work on this rather exotic setup ..."

Do you think that EFR will be made to work with Steam Deck any time soon? (assuming this is the problem and I may be wrong).

**Comment by VinterNacht** [comment]
I can't speak for L33tman, but as one of the people involved in creating these mods, I can say it's unlikely.  Neither L33tman nor I are even certain of what the actual problem is, and I have exactly no experience with Linux.

**Comment by ncottrill** [comment]
Ok, I will let him know.

**Comment by l33tmaan** [comment]
Yeah, I'd need to merge a pull request in order for this to get resolved. I have no idea how Steam Deck works. :sweat_smile:
