### ISSUE TITLE
Unable to juice small amounts of seeds/berries, but also unable to retrieve them

### ISSUE THREAD

**Issue by Derpford** [l33tmaan/EFRecipes#15]
So apparently, there's a window where you can add stuff to the Fruitpress and turn it into a wet mash, but cannot *actually* juice it. I found this out by using a great big pile of seeds, only to find that I couldn't juice them. The mash will still spoil, of course.

Would be really nice if there weren't a minimum. Alternatively, would be nice to be able to retrieve seeds if I haven't successfully begun pressing oil.

**Comment by l33tmaan** [comment]
Pressed mash is very strange. You can't juice anything in the fruit press until it's at least half full, but there's no way to distinguish pressed mash from non-pressed mash... it's all quite janky. Works mostly fine in vanilla, but it's still weird. However, none of my mods actually touch the fruit press or the mash's class. Given how many fingers I have in various metaphorical pies, I'd rather not create a custom mash class if I can avoid it.
