### ISSUE TITLE
[1.18.5] Crash when searching for berries

### ISSUE THREAD

**Issue by vrork** [l33tmaan/EFRecipes#17]
o sure if this is your mod causing but seeing as your mod is the newest i added, i would imagine it is. Also, i think its your mod too,berry bushes arent dropping anymore when broken

[client-crash.txt](https://github.com/l33tmaan/EFRecipes/files/11520463/client-crash.txt)

happen when scrolling trough the handbook searching for berry

**Comment by l33tmaan** [comment]
I don't touch trees or bushes at all. Try Wildcraft or Wildcraft Trees instead.
