### ISSUE TITLE
Cullinary Artillery still spits out errors on servers

### ISSUE THREAD

**Issue by ncottrill** [l33tmaan/EFRecipes#18]
![image](https://github.com/l33tmaan/EFRecipes/assets/14022160/4ac65e78-84f3-4c88-bc31-8ddf80f43c1a)

Is this fixable? Sometimes the server will run with this error, other times it will not.

I'm running .NET 7 multiplayer server within Pterodactyl container system (used by many hosting companies).
VS version 1.18.6-rc.1

**Comment by l33tmaan** [comment]
This should be fixed in the latest ACA release in VS 1.18.6 (.NET 7 only)!
