### ISSUE TITLE
Crash searching creative inventory immidiately afte rentering world

### ISSUE THREAD

**Issue by sekelsta** [l33tmaan/EFRecipes#25]
I'm getting a crash on VS 1.18.15, Linux, with A Culinary Artillery 1.0.15 and Expanded Foods 1.6.8 as the only mods.
To reproduce:
Enter a world
As quickly as you can, open the creative mode inventory and type anything into the search bar
The game crashes most of the time if you were quick - but if you take more than 30 seconds or so, it probably won't crash.

Just in case this is related to processor speed or something, I'm on an i3 laptop.
[client-crash.txt](https://github.com/l33tmaan/EFRecipes/files/13256919/client-crash.txt)
[client-main.txt](https://github.com/l33tmaan/EFRecipes/files/13256920/client-main.txt)
[server-main.txt](https://github.com/l33tmaan/EFRecipes/files/13256921/server-main.txt)

**Comment by l33tmaan** [comment]
I think the game just does this if you have a bunch of content mods installed. It can take a little while to load them in. You might have more success opening this issue in the actual Vintage Story repo.
