### ISSUE TITLE
Cooked Sausages can't be used in salads and normal sausages cant be used in meat stews

### ISSUE THREAD

**Issue by remuluson2** [l33tmaan/EFRecipes#29]

**Comment by l33tmaan** [comment]
![image](https://github.com/l33tmaan/EFRecipes/assets/89751315/ec0fb245-2e4a-4bd6-91a5-8ddf34e0e20d)

![image](https://github.com/l33tmaan/EFRecipes/assets/89751315/d377ebdf-1ae9-4643-a643-e0350954fd76)

Seems to be working on my machine? Are you still having this problem?

**Comment by remuluson2** [comment]
Maybe it got fixed sometime. I made this issue long time ago


sob., 16 mar 2024, 01:42 użytkownik l33tmaan ***@***.***>
napisał:

**Comment by l33tmaan** [comment]
I'll go ahead and close this out, but submit a new ticket if you see this happening again!
