### ISSUE TITLE
Cold Pasta as well as recipes that use a starting ingredient that contain other ingredients don't display correctly.

### ISSUE THREAD

**Issue by LastXsile** [l33tmaan/EFRecipes#33]
Using a cooked pasta from any grain will not display a functional recipe. Still using the mixing bowl and waiting till it finishes with no displayed progress or animation it will still produce a meal but with no name or description and only the bowl will have the nutrients displayed with no name. When on a shelf it shows the ingredients but not the meal type. Reproduced using just vanilla and expanded foods and its requirement mod. If you need any information i will be glad to send it.

**Comment by LastXsile** [comment]
Just to note using spawned in items from creative displays plain pasta correctly.

**Comment by l33tmaan** [comment]
I've been able to make pasta from scratch and it cooks fine. Is this still happening?

**Comment by LastXsile** [comment]
This seems to have been fixed and I believe this was a desync issue when a
client joined a server then reconnected the recipie wouldn't display
correctly.

**Comment by l33tmaan** [comment]
Alright, just let me know if it happens again!
